//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Instabil.java
//  @ Date : 2020. 03. 14.
//  @ Author : 
//
//




public class Instabil extends Jégmezõ {
	private int teherbírás;
	public void átfordul() {
	}
	
	public void rálép(Szereplõ sz) {
	}
}
