//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jelzõfény.java
//  @ Date : 2020. 03. 14.
//  @ Author : 
//
//




public class Jelzõfény extends Alkatrész {
}
